### PR TITLE
feat: add `version`/`DOCKER_API_VERSION` option

### PR DESCRIPTION
**Pull request by knownasilya**
See `docker5` example in https://www.npmjs.com/package/dockerode#getting-started

Hope you're doing well @kfatehi 😃

### CODE REVIEW

**Comment by kfatehi** [comment]
@knownasilya thank you, hope you're well too :]

**Comment by knownasilya** [comment]
Sweet, could you publish a new version of this? Thanks!

**Comment by knownasilya** [comment]
There is this http://blog.npmjs.org/post/158718200065/announcing-free-orgs

**Comment by kfatehi** [comment]
i've published v1.1.5 to npm just now

**Pull request merged**
